# APPLICATION CONFIGURATION
spring.application.name=01_planto_project

# Active Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# MONGODB CONFIGURATION
spring.data.mongodb.uri=${MONGODB_URI}
spring.jpa.hibernate.ddl-auto=create-drop

# JWT CONFIGURATION
planto.app.jwtSecret=${SECRET_KEY}
planto.app.jwtExpirationMs=300000

planto.app.jwtRefreshSecret=${REFRESH_SECRET_KEY}
planto.app.jwtRefreshExpirationMs=604800000

app.jwt.refresh-token-expiration-days=7
app.jwt.refresh-cookie-name=refreshToken

# IMAGEKIT CONFIGURATION
imgkit.urlEndpoint=${ImageKit_UrlEndpoint}
imgkit.privateKey=${ImageKit_PrivKey}
imgkit.publicKey=${ImageKit_PubKey}

# KAFKA CONFIGURATION (Aiven + Local)
# Kafka Bootstrap Server
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# SSL Configuration
spring.kafka.properties.security.protocol=${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
spring.kafka.ssl.trust-store-password=${KAFKA_TRUSTSTORE_PASSWORD:changeit}
spring.kafka.ssl.key-store-password=${KAFKA_KEYSTORE_PASSWORD:changeit}
spring.kafka.ssl.key-store-type=PKCS12

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Consumer Configuration
spring.kafka.consumer.group-id=order-email-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Kafka Topic
kafka.topic.order-created=order.created

# LOGGING CONFIGURATION
logging.level.planto_project=DEBUG
logging.level.planto_project.security=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.io.jsonwebtoken=DEBUG

# CORS Logging
logging.level.org.springframework.web.filter.CorsFilter=DEBUG
logging.level.org.springframework.web.servlet.config.annotation.CorsRegistry=DEBUG
logging.level.org.springframework.web.cors=DEBUG

# MongoDB Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.query=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoDbFactory=DEBUG

# Kafka Logging
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=INFO