# Kafka Bootstrap
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# SSL
spring.kafka.properties.security.protocol=SSL
spring.kafka.ssl.key-store-type=PKCS12


logging.level.planto_project=INFO
logging.level.org.apache.kafka=INFO